import axios from 'axios';
import Head from 'next/head';
import { useRouter } from 'next/router';
import React, { useEffect, useState } from 'react';
import { Nav } from '../../components/Nav/Nav';
import DefaultLayout from '../../layouts/Default';

interface CatProps {}

interface Response {
  id: number;
  name: string;
  phone: string;
  email: string;
  image: {
    alt: string;
    url: string;
  };
  description: string;
}

const Cat: React.FC<CatProps> = ({}) => {
  const [cat, setCat] = useState<Response | null>(null);

  const router = useRouter();
  const { id } = router.query;

  const fetchCate = async () => {
    const response = await axios.get(`/api/cats/${id}`);
    const data: Response = response.data;
    setCat(data);
  };

  useEffect(() => {
    fetchCate();
  }, []);

  return (
    <div>
      <Head>
        <title>{id}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        {cat && (
          <div className="container mt-5" style={{ display: 'flex' }}>
            <img src={cat.image.url} alt={cat.image.alt} />
            <div className="mx-5">
              <h1>{cat.name}</h1>
              <p>{cat.description} </p>
            </div>
          </div>
        )}
      </DefaultLayout>
    </div>
  );
};

export default Cat;
