import type { NextPage } from 'next';
import Head from 'next/head';
import { Nav } from '../components/Nav/Nav';
import styles from '../styles/Home.module.css';

import { Jumbotron } from '../components/Jumbotron.js/Jumbotron';
import DefaultLayout from '../layouts/Default';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
        <Jumbotron />
      </DefaultLayout>
    </div>
  );
};

export default Home;
